// <auto-generated />
namespace S00148095Week6Lab2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserFieldsAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserFieldsAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201711101121118_UserFieldsAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
